### ISSUE TITLE
Issues related to creating platform-sc deployment

### ISSUE THREAD

**Issue by jessebrennan** [DataBiosphere/azul#1520]
- [x] Change storage backend bucket name environment variable to something that isn't Terraform specific (#1527)
- [x] Eradicate all HCA specifics from the top-level environment file (#1528)
- [x] Remove deployment dirs other than `dev` on the non-HCA `develop` branch (https://github.com/DataBiosphere/azul/commit/7eb5901a34681a9fcfd6ec99478ec37eaa3d5769)
- [x] Mention backend bucket in README's deployment instructions (#1530)
- [x] Fix boto credential caching so that a MFA code isn't needed for every boto command. More details on this issue and the workaround are https://github.com/boto/boto3/issues/1179 (https://github.com/DataBiosphere/azul/issues/1534)
- [x] AWS region should be specified in `environment`, not `environment.local` (https://github.com/DataBiosphere/azul/commit/8f69f0c6e623fb0eef15c51270ca75ef43c2ec56)
- [x] Remove deployment dirs for non-dev deployments on non-hca branches (dupe, see above)

**Comment by hannes-ucsc** [comment]
All items have either been fixed or tickets have been created.
