### ISSUE TITLE
Add pagination to dashboard service

### ISSUE THREAD

**Issue by cricketsloan** [DataBiosphere/azul#16]
as an end user I would like  to be able to page through search results in the fie browser and handle searches that exceed the ES limit
 Boardwalk backend

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/AZUL-16)
┆Project Name: azul
┆Issue Number: AZUL-16

**Comment by cricketsloan** [comment]
➤ Kevin Osborn commented:

* [x] Create a large test input index file 
  * [ ] implement the search_after method in ES (in Kibana)
  * [ ]  wrap up in a Python method

**Comment by cricketsloan** [comment]
➤ Cricket Alicia Sloan commented:

@caaespin I am putting this into your court for overall design plan.  We still think it is important
