### ISSUE TITLE
Ensure GitLab data volume on dev and prod has enough space

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#4195]
Manually grow the volume by 50% when it is 80% full. Check weekly.

- [ ] Create Slack reminder.
- [ ] Check and grow the volume once (even if sufficient space is available) and take notes (df, stop instance, make snapshot, grow volume, start instance)
- [ ] Transfer notes to operator manual and document the procedure

Once those two items are complete, this ticket stays open and is relabled `infra` `task` `operator`.

**Comment by nolunwa-ucsc** [comment]
@hannes-ucsc putting this in triage as this is a POAM finding.

> From Fortreum
> 1. Based on documentation examined and personnel interviewed, Fortreum determined that UCSC accounts for capacity planning within AWS by scaling the systems/storage automatically as needed. There is a plan to implement a manual review of remaining disk space for GitHub. A CloudWatch metric alarm is planned to be configured for this to notify the team when disk space is nearing capacity."

**Comment by dsotirho-ucsc** [comment]
@hannes-ucsc: "We didn't solve this as described but used a CloudWatch metric alarm instead. That eliminates the need to manually check the volume. Converted this to an epic and added the relevant tickets as children."
