### ISSUE TITLE
Convert GitHub milestones to ZenHub releases

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#5603]
GitHub milestones only allow for reports per project. ZenHub releases offers reports across all projects.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by dsotirho-ucsc** [comment]
Created & assigned [releases](https://app.zenhub.com/workspaces/team-boardwalk-5d680d7e3eeb5f1bbdf5668f/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvOTYwNTE) to all tickets with [milestones](https://github.com/DataBiosphere/azul/milestones?direction=asc&sort=title&state=open).

| Name | Start | End | # Tickets |
| -- | -- | -- | -- |
| AnVIL Beta Release | 2023-10-04 | 2023-11-30 | 33 |
| AnVIL Public Release | 2023-05-02 | 2023-09-30 | 27 |
| Compliance mitigation 23/07 | 2023-06-26 | 2023-07-01 | 7 |
| Compliance mitigation 23/08 | 2023-06-26 | 2023-08-01 | 44 |
| Compliance mitigation 23/09 | 2023-06-26 | 2023-09-01 | 15 |
| Compliance mitigation 23/10 | 2023-06-26 | 2023-10-01 | 36 |
| Compliance mitigation 23/11 | 2023-06-26 | 2023-11-01 | 0 |
| Compliance mitigation 23/12 | 2023-06-26 | 2023-12-01 | 2 |
| Compliance mitigation 24/01 | 2023-06-26 | 2024-01-01 | 14 |
| Compliance mitigation 24/02 | 2023-06-26 | 2024-02-01 | 0 |
| Compliance mitigation 24/03 | 2023-06-26 | 2024-03-01 | 0 |
| Compliance mitigation 24/04 | 2023-06-26 | 2024-04-01 | 1 |
| Compliance mitigation 24/05 | 2023-06-26 | 2024-05-01 | 0 |
| Compliance mitigation 24/06 | 2023-06-26 | 2024-06-01 | 0 |
| HCA Managed Access Launch | 2023-10-05 | 2024-03-29 | 0 |
| HCA Managed Access Pilot Release | 2023-10-05 | 2023-11-30 | 2 |

**Comment by achave11-ucsc** [comment]
@hannes-ucsc: "Looks good. Assignee to now remove the milestones from issues that have the corresponding release, and to delete any milestones for which there is a release and has no tickets."

**Comment by dsotirho-ucsc** [comment]
done.
