### ISSUE TITLE
Simplify and streamline operator items in PR checklist

### ISSUE THREAD

**Issue by hannes-ucsc** [DataBiosphere/azul#5978]
The conditions as to if and when to deploy the `gitlab` and `shared` components, and when/where/how to reindex, are not clearly or consistently represented in the PR checklist. By adding dedicated labels to reflect these conditions, and making CL items conditional on these labels, we can eliminate the need for the operator to make complex decisions when they work through the checklist, offload that reasoning to the PR author, and require fewer one-off additions of items to the checklist. There's also a kitchen sink of smaller improvements I want to make, like moving the security design review from issues to PRs.

This will also pave the way to handling two separate Azul instances in a single production zone (the production instances for HCA and LungMap) as will be implemented in #5877.

- [ ] Security design review completed; the Resolution of this issue does **not** …
  - [ ] … affect authentication; for example:
    - OAuth 2.0 with the application (API or Swagger UI)
    - Authentication of developers with Google Cloud APIs
    - Authentication of developers with AWS APIs
    - Authentication with a GitLab instance in the system
    - Password and 2FA authentication with GitHub
    - API access token authentication with GitHub
    - Authentication with 
  - [ ] … affect the permissions of internal users like access to
    - Cloud resources on AWS and GCP
    - GitLab repositories, projects and groups, administration
    - an EC2 instance via SSH
    - GitHub issues, pull requests, commits, commit statuses, wikis, repositories, organizations
  - [ ] … affect the permissions of external users like access to
    - TDR snapshots
  - [ ] … affect permissions of service or bot accounts
    - Cloud resources on AWS and GCP
  - [ ] … affect audit logging in the system, like
    - adding, removing or changing a log message that represents an auditable event
    - changing the routing of log messages through the system
  - [ ] … affect monitoring of the system
  - [ ] … introduce a new software dependency like
    - Python packages on PYPI
    - Command-line utilities
    - Docker images
    - Terraform providers
  - [ ] … add an interface that exposes sensitive or confidential data at the security boundary
  - [ ] … affect the encryption of data at rest
  - [ ] … require persistence of sensitive or confidential data that might require encryption at rest
  - [ ] … require unencrypted transmission of data within the security boundary
  - [ ] … affect the network security layer; for example by 
    - modifying, adding or removing firewall rules
    - modifying, adding or removing security groups
    - changing or adding a port a service, proxy or load balancer listens on
- [ ] Documentation on any unchecked boxes is provided in comments below

**Comment by hannes-ucsc** [comment]
For demo, walk through normal, upgrade and promotion PR checklists. Note that there are some older tickets that failed to be demoed, that should be demoable now.
