### ISSUE TITLE
Even more checklist improvements

### ISSUE THREAD

**Issue by dsotirho-ucsc** [DataBiosphere/azul#6035]
```diff
Index: .github/PULL_REQUEST_TEMPLATE/upgrade.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.github/PULL_REQUEST_TEMPLATE/upgrade.md b/.github/PULL_REQUEST_TEMPLATE/upgrade.md
--- a/.github/PULL_REQUEST_TEMPLATE/upgrade.md	(revision 90b352fbf0870af81d296d015ff7c1919c900eb4)
+++ b/.github/PULL_REQUEST_TEMPLATE/upgrade.md	(date 1710280573952)
@@ -115,8 +115,8 @@
 ### Operator
 
 - [ ] Ran `script/export_inspector_findings.py` against `anvilprod`, imported results to [Google Sheet](https://docs.google.com/spreadsheets/d/1RWF7g5wRKWPGovLw4jpJGX_XMi8aWLXLOvvE5rxqgH8) and posted screenshot of relevant<sup>1</sup> findings as a comment on the connected issue.
-- [ ] Propagated the `deploy:shared`, `deploy:gitlab`, `deploy:runner`, `reindex:partial` and `reindex:prod` labels to the next promotion PR <sub>or this PR carries none of these labels</sub>
-- [ ] Propagated any specific instructions related to the `deploy:shared`, `deploy:gitlab`, `deploy:runner`, `reindex:partial` and `reindex:prod` labels from the description of this PR to that of the next promotion PR <sub>or this PR carries none of these labels</sub>
+- [ ] Propagated the `deploy:shared`, `deploy:gitlab`, and `deploy:runner` labels to the next promotion PR <sub>or this PR carries none of these labels</sub>
+- [ ] Propagated any specific instructions related to the `deploy:shared`, `deploy:gitlab`, and `deploy:runner` labels from the description of this PR to that of the next promotion PR <sub>or this PR carries none of these labels</sub>
 - [ ] PR is assigned to only the system administrator
 
 <sup>1</sup>A relevant finding is a high or critical vulnerability in an image
Index: .github/PULL_REQUEST_TEMPLATE/promotion.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.github/PULL_REQUEST_TEMPLATE/promotion.md b/.github/PULL_REQUEST_TEMPLATE/promotion.md
--- a/.github/PULL_REQUEST_TEMPLATE/promotion.md	(revision 90b352fbf0870af81d296d015ff7c1919c900eb4)
+++ b/.github/PULL_REQUEST_TEMPLATE/promotion.md	(date 1710281028726)
@@ -29,9 +29,9 @@
 ### Author (upgrading deployments)
 
 - [ ] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
-- [ ] This PR is labeled `deploy:shared` <sub>or does not modify `image_manifests.json`, and does not require deploying the `shared` component for any other reason</sub>
-- [ ] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
-- [ ] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>
+- [ ] This PR is labeled `deploy:shared`  # Confusing escape hatch
+- [ ] This PR is labeled `deploy:gitlab`  # Confusing escape hatch
+- [ ] This PR is labeled `deploy:runner`  # Confusing escape hatch
 
 
 ### System administrator (after approval)
Index: .github/pull_request_template.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.github/pull_request_template.md b/.github/pull_request_template.md
--- a/.github/pull_request_template.md	(revision 90b352fbf0870af81d296d015ff7c1919c900eb4)
+++ b/.github/pull_request_template.md	(date 1710280006075)
@@ -22,6 +22,9 @@
 - [ ] PR title references all connected issues
 - [ ] For each connected issue, there is at least one commit whose title references that issue
 
+<sup>1</sup> when the issue title describes a problem, the corresponding PR
+title is `Fix: ` followed by the issue title
+
 
 ### Author (partiality)
 
@@ -29,9 +32,6 @@
 - [ ] This PR is labeled `partial` <sub>or completely resolves all connected issues</sub>
 - [ ] This PR partially resolves each of the connected issues <sub>or does not have the `partial` label</sub>
 
-<sup>1</sup> when the issue title describes a problem, the corresponding PR
-title is `Fix: ` followed by the issue title
-
 
 ### Author (chains)
 
@@ -46,6 +46,7 @@
 - [ ] This PR is labeled `reindex:dev` <sub>or does not require reindexing `dev`</sub>
 - [ ] This PR is labeled `reindex:anvildev` <sub>or does not require reindexing `anvildev`</sub>
 - [ ] This PR is labeled `reindex:anvilprod` <sub>or does not require reindexing `anvilprod`</sub>
+- [ ] This PR is labeled `reindex:prod` <sub>or does not require reindexing `prod`</sub>
 - [ ] This PR is labeled `reindex:partial` and its description documents the specific reindexing procedure for `dev`, `anvildev`, `anvilprod` and `prod` <sub>or requires a full reindex or carries none of the labels `reindex:dev`, `reindex:anvildev`, `reindex:anvilprod` and `reindex:prod`</sub>
 - [ ] This PR and its connected issues are labeled `API` <sub>or this PR does not modify a REST API</sub>
 - [ ] Added `a` (`A`) tag to commit title for backwards (in)compatible changes <sub>or this PR does not modify a REST API</sub>
@@ -54,20 +55,15 @@
 
 ### Author (upgrading deployments)
 
+- [ ] Ran `make image_manifests.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
 - [ ] Documented upgrading of deployments in UPGRADING.rst <sub>or this PR does not require upgrading deployments</sub>
 - [ ] Added `u` tag to commit title <sub>or this PR does not require upgrading deployments</sub>
-- [ ] Ran `make image_manifests.json` and committed the resulting changes <sub>or this PR does not modify `azul_docker_images`, or any other variables referenced in the definition of that variable</sub>
 - [ ] This PR is labeled `upgrade` <sub>or does not require upgrading deployments</sub>
 - [ ] This PR is labeled `deploy:shared` <sub>or does not modify `image_manifests.json`, and does not require deploying the `shared` component for any other reason</sub>
 - [ ] This PR is labeled `deploy:gitlab` <sub>or does not require deploying the `gitlab` component</sub>
 - [ ] This PR is labeled `deploy:runner` <sub>or does not require deploying the `runner` image</sub>
 
 
-### Author (operator tasks)
-
-- [ ] Added checklist items for additional operator tasks <sub>or this PR does not require additional tasks</sub>
-
-
 ### Author (hotfixes)
 
 - [ ] Added `F` tag to main commit title <sub>or this PR does not include permanent fix for a temporary hotfix</sub>
@@ -83,11 +79,6 @@
 - [ ] `make integration_test` passes in personal deployment <sub>or this PR does not modify functionality that could affect the IT outcome</sub>
 
 
-### Peer reviewer (after requesting changes)
-
-Uncheck the *Author (before every review)* checklists.
-
-
 ### Peer reviewer (after approval)
 
 - [ ] PR is not a draft
@@ -96,18 +87,13 @@
 - [ ] PR is assigned to only the system administrator
 
 
-### System administrator (after requesting changes)
-
-Uncheck the *before every review* checklists. Update the `N reviews` label.
-
-
 ### System administrator (after approval)
 
 - [ ] Actually approved the PR
 - [ ] Labeled connected issues as `demo` or `no demo`
 - [ ] Commented on connected issues about demo expectations <sub>or all connected issues are labeled `no demo`</sub>
 - [ ] Decided if PR can be labeled `no sandbox`
-- [ ] A comment to this PR details the completed security design review <sub>or this PR is a promotion or a backport</sub>
+- [ ] A comment to this PR details the completed security design review  # TODO make conditional
 - [ ] PR title is appropriate as title of merge commit
 - [ ] `N reviews` label is accurate
 - [ ] Moved ticket to *Approved* column
@@ -118,7 +104,6 @@
 
 - [ ] Checked `reindex:…` labels and `r` commit title tag
 - [ ] Checked that demo expectations are clear <sub>or all connected issues are labeled `no demo`</sub>
-- [ ] PR has checklist items for upgrading instructions <sub>or PR is not labeled `upgrade`</sub>
 - [ ] Squashed PR branch and rebased onto `develop`
 - [ ] Sanity-checked history
 - [ ] Pushed PR branch to GitHub
@@ -129,7 +114,7 @@
 - [ ] Ran `_select anvilprod.shared && CI_COMMIT_REF_NAME=develop make -C terraform/shared apply_keep_unused` <sub>or this PR is not labeled `deploy:shared`</sub>
 - [ ] Ran `_select anvilprod.gitlab && CI_COMMIT_REF_NAME=develop make -C terraform/gitlab apply` <sub>or this PR is not labeled `deploy:gitlab`</sub>
 - [ ] Checked the items in the next section <sub>or this PR is labeled `deploy:gitlab`</sub>
-- [ ] Assigned system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>
+- [ ] PR is assigned to only the system administrator <sub>or this PR is not labeled `deploy:gitlab`</sub>
 
 
 ### System administrator

```

**Comment by dsotirho-ucsc** [comment]
Assignee to consider next steps.

**Comment by achave11-ucsc** [comment]
Also consider …

```diff
Index: .github/pull_request_template.md.template.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.github/pull_request_template.md.template.py b/.github/pull_request_template.md.template.py
--- a/.github/pull_request_template.md.template.py	(revision 127d9520acc69d1e59f5f9d6d99f555b7e3c7085)
+++ b/.github/pull_request_template.md.template.py	(date 1709590189373)
@@ -522,10 +522,6 @@
                     'content': 'Ticket is in *Review requested* column'
                 },
                 {
-                    'type': 'cli',
-                    'content': 'Requested review from system administrator'
-                },
-                {
                     'type': 'cli',
                     'content': 'PR is assigned to only the system administrator'
                 }
```

… it seems redundant since the code owner gets automatically requested for review when the PR changes from draft to ready for review.

**Comment by hannes-ucsc** [comment]
~Also add CL item to perform GitLab backups as part of the upgrade PR.~

See #5839

**Comment by hannes-ucsc** [comment]
```diff
Index: .github/ISSUE_TEMPLATE/upgrade.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/.github/ISSUE_TEMPLATE/upgrade.md b/.github/ISSUE_TEMPLATE/upgrade.md
--- a/.github/ISSUE_TEMPLATE/upgrade.md	(revision 235466d5d994cbe84cd44e5807e9b171e61c10e6)
+++ b/.github/ISSUE_TEMPLATE/upgrade.md	(date 1711154543422)
@@ -33,9 +33,6 @@
   - [ ] … update to [GitLab](https://hub.docker.com/r/gitlab/gitlab-ce/tags) & [GitLab runner images](https://hub.docker.com/r/gitlab/gitlab-runner/tags) <sub>or no update available</sub>
   - [ ] … update to [ClamAV image](https://hub.docker.com/r/clamav/clamav/tags) <sub>or no update available</sub>
   - [ ] … update to [GitLab AMI](https://github.com/DataBiosphere/azul/blob/develop/OPERATOR.rst#updating-the-ami-for-gitlab-instances) <sub>or no update available</sub>
-- [ ] Delete obsolete image tags from DockerHub (but consider that `prod` may not use the latest image) … 
-  - [ ] … for [PyCharm image](https://hub.docker.com/repository/docker/ucscgi/azul-pycharm)
-  - [ ] … for [Elasticsearch image](https://hub.docker.com/repository/docker/ucscgi/azul-elasticsearch)
 - [ ] Created tickets for any deferred updates to …
   - [ ] … to next major or minor Python version <sub>or such ticket already exists</sub>
   - [ ] … to next major Docker version <sub>or such ticket already exists</sub>
```

**Comment by achave11-ucsc** [comment]
Also update issue template for ES updates:

```
- [x] Update `azul-index-dev` <sub>or `azul-index-dev` is on the latest version</sub>
- [x] There are no outstanding notifications in `azul-index-dev`
- [x] Update `azul-index-anvildev` <sub>or `azul-index-anvildev` is on the latest version</sub>
- [x] There are no outstanding notifications in `azul-index-anvildev`
- [x] Update `azul-index-anvilprod` <sub>or `azul-index-anvilprod` is on the latest version</sub>
- [x] There are no outstanding notifications in `azul-index-anvilprod`
- [x] Devs confirmed personal deployments collocated with `dev` are idle <sub>or `azul-index-sandbox` is on the latest version</sub>
- [x] Update `azul-index-sandbox` <sub>or `azul-index-sandbox` is on the latest version</sub>
- [x] There are no outstanding notifications in `azul-index-sandbox`
- [x] Devs confirmed personal deployments collocated with `anvildev` are idle <sub>or `azul-index-anvilbox` is on the latest version</sub>
- [x] Update `azul-index-anvilbox` <sub>or `azul-index-anvilbox` is on the latest version</sub>
- [x] There are no outstanding notifications in `azul-index-anvilbox`
- [x] Devs confirmed personal deployments collocated with `anvilprod` are idle <sub>or `azul-index-hammerbox` is on the latest version</sub>
- [x] Update `azul-index-hammerbox` <sub>or `azul-index-hammerbox` is on the latest version</sub>
- [x] There are no outstanding notifications in `azul-index-hammerbox`
- [x] Update `azul-index-prod` <sub>or `azul-index-prod` is on the latest version</sub>
- [x] There are no outstanding notifications in `azul-index-prod`
```
