### ISSUE TITLE
Upgrade dependencies 2024-06-24

### ISSUE THREAD

**Issue by azul-group** [DataBiosphere/azul#6356]
- [x] Update [PyCharm image](https://github.com/DataBiosphere/azul-docker-pycharm)
  - [x] Bump [base image](https://hub.docker.com/_/debian/tags?name=bullseye) tag (only same Debian release), if possible
  - [x] Bump upstream version, if possible
  - [x] Bump internal version
  - [x] Remove unused dependencies with high or critical CVEs
  - [x] Push commit to GitHub (directly to `master` branch, no PR needed)
  - [x] GH Action workflow succeeded
  - [x] Image is available on [DockerHub](https://hub.docker.com/repository/docker/ucscgi/azul-pycharm) 
- [x] Update [Elasticsearch image](https://github.com/DataBiosphere/azul-docker-elasticsearch)
  - [x] Bump [base image](https://hub.docker.com/_/elasticsearch/tags) tag (only minor and patch versions), if possible
  - [x] Bump internal version 
  - [x] Remove unused dependencies with high or critical CVEs
  - [x] Push commit to GitHub (directly to `main` branch, no PR needed)
  - [x] GH Action workflow succeeded
  - [x] Image is available on [DockerHub](https://hub.docker.com/repository/docker/ucscgi/azul-elasticsearch) 
- [x] Update [BigQuery Emulator image](https://github.com/DataBiosphere/azul-bigquery-emulator)
  - [x] Bump [base image](https://hub.docker.com/_/debian/tags) tag, if possible
  - [x] Bump internal version 
  - [x] Push commit to GitHub (directly to `azul` branch, no PR needed)
  - [x] GH Action workflow succeeded
  - [x] Image is available on [DockerHub](https://hub.docker.com/repository/docker/ucscgi/azul-bigquery-emulator) 
- [x] Create Azul PR, connected to this issue, with … 
  - [x] … changes to `requirements*.txt` from open Dependabot PRs, one commit per PR
  - [x] … update to [Python](https://hub.docker.com/_/python/tags) (only patch versions) <sub>or no update available</sub>
  - [x] … update to [Terraform](https://hub.docker.com/r/hashicorp/terraform/tags) (only patch versions) <sub>or no update available</sub>
  - [x] … new [PyCharm image](https://hub.docker.com/repository/docker/ucscgi/azul-pycharm)
  - [x] … new [Elasticsearch image](https://hub.docker.com/repository/docker/ucscgi/azul-elasticsearch)
  - [x] … new [BigQuery Emulator image](https://hub.docker.com/repository/docker/ucscgi/azul-bigquery-emulator)
  - [x] … update to [Docker images](https://hub.docker.com/_/docker/tags) (only minor and patch versions) <sub>or no update available</sub>
  - [x] … update to [GitLab](https://hub.docker.com/r/gitlab/gitlab-ce/tags) & [GitLab runner images](https://hub.docker.com/r/gitlab/gitlab-runner/tags) <sub>or no update available</sub>
  - [x] … update to [ClamAV image](https://hub.docker.com/r/clamav/clamav/tags) <sub>or no update available</sub>
  - [x] … update to [GitLab AMI](https://github.com/DataBiosphere/azul/blob/develop/OPERATOR.rst#updating-the-ami-for-gitlab-instances) <sub>or no update available</sub>
- [x] Created tickets for any deferred updates to …
  - [x] … to next major or minor Python version <sub>or such ticket already exists</sub> https://github.com/DataBiosphere/azul/issues/5736
  - [x] … to next major Docker version <sub>or such ticket already exists</sub> https://github.com/DataBiosphere/azul/issues/6230 https://github.com/DataBiosphere/azul/issues/6379
  - [x] … to next major or minor Terraform version <sub>or such ticket already exists</sub> https://github.com/DataBiosphere/azul/issues/5893 https://github.com/DataBiosphere/azul/issues/6380 https://github.com/DataBiosphere/azul/issues/6381

**Comment by dsotirho-ucsc** [comment]
Google sheet updated: [Inspector Findings (tab: 2024-06-24)](https://docs.google.com/spreadsheets/d/1RWF7g5wRKWPGovLw4jpJGX_XMi8aWLXLOvvE5rxqgH8/edit?gid=2015367390#gid=2015367390)

![Screenshot 2024-07-08 at 3 58 26 PM](https://github.com/DataBiosphere/azul/assets/46407464/170dd17c-9547-4239-a6b7-417ab50e14a6)

**Comment by nolunwa-ucsc** [comment]
@dsotirho-ucsc for all the new Inspector finding have you opened tickets for the remediations?

**Comment by nolunwa-ucsc** [comment]
@dsotirho-ucsc ok make sense and thanks for clarifying
